"""fix

Revision ID: e67768b19106
Revises: 5f6d1bd17931
Create Date: 2024-08-09 09:38:42.949829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'e67768b19106'
down_revision = '5f6d1bd17931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_responses', schema=None) as batch_op:
        batch_op.alter_column('choices',
               existing_type=sqlite.JSON(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_responses', schema=None) as batch_op:
        batch_op.alter_column('choices',
               existing_type=sa.String(length=100),
               type_=sqlite.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###
